export interface CityData {
  name: string
  country: string
}

export const popularCities: CityData[] = [
  { name: "London", country: "GB" },
  { name: "New York", country: "US" },
  { name: "Tokyo", country: "JP" },
  { name: "Paris", country: "FR" },
  { name: "Berlin", country: "DE" },
  { name: "Sydney", country: "AU" },
  { name: "Rome", country: "IT" },
  { name: "Madrid", country: "ES" },
  { name: "Moscow", country: "RU" },
  { name: "Beijing", country: "CN" },
  { name: "Cairo", country: "EG" },
  { name: "Rio de Janeiro", country: "BR" },
  { name: "Dubai", country: "AE" },
  { name: "Mumbai", country: "IN" },
  { name: "Toronto", country: "CA" },
  { name: "Singapore", country: "SG" },
  { name: "Istanbul", country: "TR" },
  { name: "Bangkok", country: "TH" },
  { name: "Amsterdam", country: "NL" },
  { name: "Seoul", country: "KR" },
  { name: "Mexico City", country: "MX" },
  { name: "Stockholm", country: "SE" },
  { name: "Vienna", country: "AT" },
  { name: "Athens", country: "GR" },
  { name: "Prague", country: "CZ" },
  { name: "Warsaw", country: "PL" },
  { name: "Budapest", country: "HU" },
  { name: "Dublin", country: "IE" },
  { name: "Helsinki", country: "FI" },
  { name: "Lisbon", country: "PT" },
  { name: "Oslo", country: "NO" },
  { name: "Copenhagen", country: "DK" },
  { name: "Brussels", country: "BE" },
  { name: "Zurich", country: "CH" },
  { name: "San Francisco", country: "US" },
  { name: "Los Angeles", country: "US" },
  { name: "Chicago", country: "US" },
  { name: "Miami", country: "US" },
  { name: "Vancouver", country: "CA" },
  { name: "Montreal", country: "CA" },
  { name: "Barcelona", country: "ES" },
  { name: "Milan", country: "IT" },
  { name: "Munich", country: "DE" },
  { name: "Frankfurt", country: "DE" },
  { name: "Melbourne", country: "AU" },
  { name: "Auckland", country: "NZ" },
  { name: "Wellington", country: "NZ" },
  { name: "Hong Kong", country: "HK" },
  { name: "Shanghai", country: "CN" },
  { name: "Taipei", country: "TW" },
]
